name: Checks

on:
  pull_request:
  workflow_dispatch:

jobs:
  format:
    name: ğŸ’… Format
    uses: ./.github/workflows/node-ci.yml
    with:
      run-command: |
        npm run format:check
  lint:
    name: ğŸ§ª Lint
    uses: ./.github/workflows/node-ci.yml
    with:
      run-command: |
        npm run lint:check

  type:
    name: ğŸ” Type
    uses: ./.github/workflows/node-ci.yml
    with:
      run-command: |
        npm run type:check
  build:
    name: ğŸ”¨ Build
    uses: ./.github/workflows/node-ci.yml
    with:
      run-command: |
        npm run build

  knip:
    name: âœ‚ï¸ Knip
    uses: ./.github/workflows/node-ci.yml
    with:
      run-command: |
        npm run knip:check

  lint-actions:
    name: ğŸ§ª Lint Actions
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ’» Checkout repo
        uses: actions/checkout@v6

      - name: â¬‡ï¸ Download actionlint
        id: get_actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
        shell: bash

      - name: ğŸ” Check workflow files
        run: ${{ steps.get_actionlint.outputs.executable }} -color
        shell: bash
