name: Checks

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  code-checks:
    name: Code checks
    runs-on: ubuntu-latest

    steps:
      - name: â¬‡ï¸ Checkout code
        uses: actions/checkout@v6

      - name: ğŸ“¦ Setup Node and PNPM
        uses: pnpm/action-setup@v4

      - name: ğŸ”§ Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: "./.nvmrc"
          cache: "pnpm"

      - name: ğŸ“¥ Install dependencies
        run: pnpm install

      - name: ğŸ’… Run formatter
        run: pnpm format:check

      - name: ğŸ§ª Run linter
        run: pnpm lint:check

      - name: ğŸ” Type check
        run: pnpm type:check

      - name: ğŸ”¨ Build check
        run: pnpm build

      - name: âœ‚ï¸ Run knip
        run: pnpm run knip:check

  lint-actions:
    name: Lint Actions
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ’» Checkout repo
        uses: actions/checkout@v6

      - name: â¬‡ï¸ Download actionlint
        id: get_actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
        shell: bash

      - name: ğŸ” Check workflow files
        run: ${{ steps.get_actionlint.outputs.executable }} -color
        shell: bash
