name: Check PR Label and Update PR Description

on:
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled
      - edited
    branches:
      - develop
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: write

jobs:
  check-label:
    name: PR Label
    runs-on: ubuntu-latest
    steps:
      - name: Update PR description to check "Added label" box
        uses: actions/github-script@v8
        with:
          script: |
            const requiredLabels = new Set(["fix", "change", "feature", "enhancement", "technical-change", "dependencies", "tests", "docs"]);
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            if (!context.payload.pull_request || !context.payload.pull_request.number) { return; }
            const prNumber = context.payload.pull_request.number;
            const labels = context.payload.pull_request.labels.map(label => label.name);
            const labelValid = labels.some(label => requiredLabels.has(label));

            if (!labelValid) {
              core.setFailed(`This PR is missing one of the required labels: ${[...requiredLabels].join(', ')}`);
            }
