name: Tests

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  unit:
    name: ðŸ§ª Unit
    uses: ./.github/workflows/node-ci.yml
    with:
      run-command: |
        npm run test:unit

  component:
    name: ðŸ§© Component
    uses: ./.github/workflows/node-ci.yml
    with:
      run-command: |
        npm run test:component

  integration:
    name: ðŸª¢ Integration
    uses: ./.github/workflows/node-ci.yml
    with:
      run-command: |
        npm run test:integration
